import fs from 'node:fs/promises';import path from 'node:path';import{SpreadsheetFile,Workbook}from'@oai/artifact-tool';
const root='/Users/xiaoyu/Documents/ale/repairs/build/2505-current-agent',task=path.join(root,'task'),renders=path.join(root,'workbook-renders');await fs.mkdir(renders,{recursive:true});const head={fill:'#365B69',font:{bold:true,color:'#FFFFFF'},wrapText:true},body={wrapText:true,verticalAlignment:'top',borders:{bottom:{style:'thin',color:'#D6E0E4'}}};
function add(book,name,rows,widths){const s=book.worksheets.add(name),r=s.getRangeByIndexes(0,0,rows.length,widths.length);r.values=rows;r.format=body;s.getRangeByIndexes(0,0,1,widths.length).format=head;widths.forEach((w,i)=>s.getRangeByIndexes(0,i,rows.length,1).format.columnWidth=w);r.format.autofitRows();s.freezePanes.freezeRows(1);s.showGridLines=false;}
async function finish(book,label,file){for(const s of book.worksheets.items){const p=await book.render({sheetName:s.name,autoCrop:'all',scale:1.25,format:'png'});await fs.writeFile(path.join(renders,`${label}-${s.name}.png`),new Uint8Array(await p.arrayBuffer()));}const errors=await book.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A',options:{useRegex:true,maxResults:100},maxChars:5000});await fs.writeFile(path.join(renders,`${label}.errors.ndjson`),errors.ndjson);const inspect=await book.inspect({kind:'sheet,table',include:'id,name,values',tableMaxRows:100,tableMaxCols:8,maxChars:45000});await fs.writeFile(path.join(task,`${file}.inspect.ndjson`),inspect.ndjson);const out=await SpreadsheetFile.exportXlsx(book);await out.save(path.join(task,file));}
const a=Workbook.create();add(a,'交付物答案清单',[
['交付物名称','固定路径/命名规则','用途','判定方式'],['production发布目录','output/release/production','保存Deployment、HPA与Kustomize入口','运行kubectl kustomize'],['Deployment候选','output/release/production/deployment.yaml','保留业务配置并补环境标签','与输入spec深度比较'],['HPA候选','output/release/production/hpa.yaml','落实容量组策略','与合同结构化比较'],['Kustomize入口','output/release/production/kustomization.yaml','声明两个发布对象','解析resources并执行kubectl'],['渲染清单','output/evidence/rendered.yaml','供发布负责人审阅客户端构建结果','解析对象身份'],['字段核对表','output/evidence/field_review.csv','汇总合同与保护检查','按check核对'],['发布复核','output/evidence/release_review.json','记录对象、检查状态和结论边界','读取JSON并回查清单'],['说明','output/README.txt','说明材料用途与READY边界','与实际文件互证'],
],[34,78,72,60]);add(a,'固定字段答案',[
['交付物或对象','字段路径','正确值','来源与验证'],['HPA','apiVersion','autoscaling/v2','容量策略'],['HPA','kind','HorizontalPodAutoscaler','Kubernetes对象合同'],['HPA','metadata.name与namespace','queue-worker与queue-platform','autoscaling_policy.json'],['HPA','scaleTargetRef','apps/v1、Deployment、queue-worker','容量策略'],['HPA','minReplicas与maxReplicas','4与30','autoscaling_policy.json'],['CPU指标','averageUtilization',65,'autoscaling_policy.json'],['外部指标','metric.name','queue_depth','autoscaling_policy.json'],['外部指标','averageValue',30,'autoscaling_policy.json'],['复核结果','scope','client_render_review','客户端能力边界'],['复核结果','status','READY','全部checks通过'],
],[42,58,62,72]);add(a,'固定集合答案',[
['交付物或对象','字段或集合','正确集合','判定方式'],['渲染对象','复合身份','apps/v1Deployment queue-worker、autoscaling/v2HorizontalPodAutoscaler queue-worker','集合精确匹配'],['指标','type','Resource、External','集合精确匹配'],['升降策略','policy type','Percent、Pods','分别在scaleUp和scaleDown匹配'],['公共标签','键','platform.example/environment、platform.example/owner、platform.example/cost-center','两个对象均需包含'],['Kustomize','resources','deployment.yaml、hpa.yaml','集合精确匹配'],
],[38,48,106,62]);add(a,'固定数值答案',[
['交付物或对象','字段或位置','正确值','容差','来源与验证'],['HPA','minReplicas',4,0,'autoscaling_policy.json'],['HPA','maxReplicas',30,0,'autoscaling_policy.json'],['CPU指标','averageUtilization',65,0,'autoscaling_policy.json'],['scaleDown','stabilizationWindowSeconds',300,0,'autoscaling_policy.json'],['scaleUp Percent','value',100,0,'autoscaling_policy.json'],['scaleDown Percent','value',25,0,'autoscaling_policy.json'],
],[38,52,28,22,70]);add(a,'允许变体答案',[
['对象','允许变化','不可变化','判定方式'],['YAML','键序、缩进和文档顺序可以变化','对象身份、合同字段和Deployment.spec不能变化','结构化解析比较'],['Kustomize目录','文件注释可以变化','resources只引用两个目标对象','kubectl实际构建'],['公共标签','可保留原有标签','三个合同标签不能缺失或改值','键值集合比较'],['复核说明','措辞和段落可变化','不能声称实际扩缩容已发生','人工复核与状态字段'],['CSV','行序可以变化','check、status和evidence不能变化','按check排序比较'],
],[34,82,92,64]);await finish(a,'关键标准答案','关键标准答案.xlsx');
const s=Workbook.create();add(s,'任务规格',[
['模块','规格内容'],['任务ID','queue_worker_hpa_release'],['主软件','Kubernetes'],['辅助工具','PowerShell7、kubectl.exe1.32.6、内置Kustomize5.5.0、Python3.12和PyYAML6.0.2'],['输入来源','平台容量组提供的当前对象、弹性策略和production公共标签'],['输入获取方式','从交接压缩包解压到Windows11本地目录'],['原始输入文件','current/deployment.yaml、current/hpa.yaml、autoscaling_policy.json、environment_labels.csv和README.txt'],['目标输出文件','output/release/production、output/evidence和output/README.txt'],['核心操作链','核对身份与策略→修正HPA→保护Deployment业务配置→补公共标签→组织Kustomize→kubectl构建→整理发布复核'],['HPA身份','autoscaling/v2HorizontalPodAutoscaler位于queue-platform并指向apps/v1Deployment queue-worker'],['指标合同','同时配置CPU Resource Utilization和queue_depth External AverageValue'],['行为合同','scaleUp与scaleDown的窗口、选择规则、Percent和Pods策略逐字段取自容量合同'],['Deployment边界','metadata.labels可补公共标签，spec必须与输入Deployment完全一致'],['环境标签','production、owner和cost-center取environment_labels.csv唯一production行'],['Kustomize范围','release/production只引用Deployment和HPA，kubectl客户端离线生成候选YAML'],['复核边界','检查对象身份、HPA合同、公共标签与Deployment保护；READY只代表材料可继续审阅'],['能力边界','不连接API Server，不声称HPA Controller已执行调度、指标采集或实际扩缩容'],['完成条件','kubectl构建成功，两个对象身份正确，合同检查全部通过，Deployment.spec不变'],['可验证点','对象复合身份、targetRef、副本边界、指标、behavior、标签、Deployment.spec和kubectl退出码'],['不适合作为评分点的内容','YAML键序、文档顺序、编辑器、临时目录、注释、排版和真实集群伸缩结果'],
],[34,146]);await finish(s,'任务规格转化','任务规格转化.xlsx');
