import fs from 'node:fs/promises';import path from 'node:path';import{SpreadsheetFile,Workbook}from'@oai/artifact-tool';
const root='/Users/xiaoyu/Documents/ale/repairs/build/2505-current-agent',task=path.join(root,'task'),renders=path.join(root,'workbook-renders');await fs.mkdir(renders,{recursive:true});const head={fill:'#365B69',font:{bold:true,color:'#FFFFFF'},wrapText:true},body={wrapText:true,verticalAlignment:'top',borders:{bottom:{style:'thin',color:'#D6E0E4'}}};
function add(book,name,rows,widths){const s=book.worksheets.add(name),r=s.getRangeByIndexes(0,0,rows.length,widths.length);r.values=rows;r.format=body;s.getRangeByIndexes(0,0,1,widths.length).format=head;widths.forEach((w,i)=>s.getRangeByIndexes(0,i,rows.length,1).format.columnWidth=w);r.format.autofitRows();s.freezePanes.freezeRows(1);s.showGridLines=false;}
async function finish(book,label,file){for(const s of book.worksheets.items){const p=await book.render({sheetName:s.name,autoCrop:'all',scale:1.25,format:'png'});await fs.writeFile(path.join(renders,`${label}-${s.name}.png`),new Uint8Array(await p.arrayBuffer()));}const errors=await book.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A',options:{useRegex:true,maxResults:100},maxChars:5000});await fs.writeFile(path.join(renders,`${label}.errors.ndjson`),errors.ndjson);const inspect=await book.inspect({kind:'sheet,table',include:'id,name,values',tableMaxRows:100,tableMaxCols:8,maxChars:45000});await fs.writeFile(path.join(task,`${file}.inspect.ndjson`),inspect.ndjson);const out=await SpreadsheetFile.exportXlsx(book);await out.save(path.join(task,file));}
const a=Workbook.create();add(a,'交付物答案清单',[
['交付物名称','固定路径/命名规则','用途','判定方式'],
['Deployment候选','release/production/deployment.yaml','保存业务配置与production标签','与输入Deployment结构化比较'],
['HPA候选','release/production/hpa.yaml','落实容量策略','与autoscaling_policy.json结构化比较'],
['上线Kustomize入口','release/production/kustomization.yaml','声明候选发布对象','运行kubectl kustomize'],
['撤回Deployment','release/rollback/deployment.yaml','保存当前Deployment','与输入对象结构化比较'],
['撤回HPA','release/rollback/hpa.yaml','保存当前HPA','与输入对象结构化比较'],
['撤回Kustomize入口','release/rollback/kustomization.yaml','声明撤回对象','运行kubectl kustomize'],
['上线渲染清单','rendered_production.yaml','供发布负责人查看候选对象','解析对象身份与字段'],
['撤回渲染清单','rendered_rollback.yaml','供值班负责人查看撤回对象','解析对象身份与字段'],
['变更记录','change_record.csv','记录HPA字段变化与Deployment保留状态','回查输入与候选清单'],
['发布计划','release_plan.yaml','记录窗口、影响面、上线、撤回和观察安排','与release_policy.json比较'],
['发布说明','release_notes.txt','说明材料用途与操作边界','与实际文件互证'],
],[34,78,72,64]);add(a,'固定字段答案',[
['交付物或对象','字段路径','正确值','来源'],
['release/production/hpa.yaml','apiVersion','autoscaling/v2','Kubernetes对象合同'],
['release/production/hpa.yaml','kind','HorizontalPodAutoscaler','Kubernetes对象合同'],
['release/production/hpa.yaml','metadata.name与metadata.namespace','queue-worker与queue-platform','autoscaling_policy.json'],
['release/production/hpa.yaml','spec.scaleTargetRef','apps/v1、Deployment、queue-worker','autoscaling_policy.json'],
['change_record.csv','Deployment/queue-worker的spec状态','unchanged','current/deployment.yaml'],
],[54,66,74,70]);add(a,'固定集合答案',[
['交付物或对象','字段或集合','正确集合','判定方式'],
['两份渲染清单','对象复合身份','apps/v1Deployment queue-worker、autoscaling/v2HorizontalPodAutoscaler queue-worker','分别做集合精确匹配'],
['release/production/hpa.yaml','spec.metrics.type','Resource、External','集合精确匹配'],
['release/production/hpa.yaml','升降policy type','Percent、Pods','分别在scaleUp和scaleDown匹配'],
['候选Deployment与HPA','公共标签键','platform.example/environment、platform.example/owner、platform.example/cost-center','两个对象均需包含'],
['release/production/kustomization.yaml','resources','deployment.yaml、hpa.yaml','集合精确匹配'],
['release/rollback/kustomization.yaml','resources','deployment.yaml、hpa.yaml','集合精确匹配'],
['release_plan.yaml','rollback.triggers','apply_exit_code_nonzero、hpa_condition_AbleToScale_false、hpa_condition_ScalingActive_false','集合精确匹配'],
['release_plan.yaml','observation.metric','queue_depth、cpu_utilization_percent、hpa_desired_replicas','集合精确匹配'],
],[58,50,108,64]);add(a,'固定数值答案',[
['交付物或对象','字段或位置','正确值','容差','来源'],
['release/production/hpa.yaml','spec.minReplicas',4,0,'autoscaling_policy.json'],
['release/production/hpa.yaml','spec.maxReplicas',30,0,'autoscaling_policy.json'],
['release/production/hpa.yaml','CPU averageUtilization',65,0,'autoscaling_policy.json'],
['release/production/hpa.yaml','scaleDown stabilizationWindowSeconds',300,0,'autoscaling_policy.json'],
['release/production/hpa.yaml','scaleUp Percent value',100,0,'autoscaling_policy.json'],
['release/production/hpa.yaml','scaleDown Percent value',25,0,'autoscaling_policy.json'],
['release_plan.yaml','change_window.decision_wait_minutes',10,0,'release_policy.json'],
['release_plan.yaml','observation.queue_depth.boundary',30,0,'release_policy.json'],
['release_plan.yaml','observation.cpu_utilization_percent.boundary',65,0,'release_policy.json'],
],[58,66,28,22,70]);add(a,'允许变体答案',[
['对象','允许变化','不可变化','判定方式'],
['YAML','键序、缩进和文档顺序可以变化','对象身份、合同字段和Deployment.spec不能变化','结构化解析比较'],
['Kustomize目录','文件注释可以变化','resources须引用两个目标对象','kubectl实际构建'],
['公共标签','可以保留原有标签','三个合同标签不能缺失或改值','键值集合比较'],
['发布说明','措辞和段落可以变化','不能声称实际扩缩容已发生','人工阅读并回查清单'],
['change_record.csv','行序可以变化','object、field、前后值和source的含义不能变化','按object与field比较'],
['release_plan.yaml','触发条件和观察项顺序可以变化','命令、窗口、影响面和数值边界不能变化','结构化比较'],
],[36,82,94,70]);await finish(a,'关键标准答案','关键标准答案.xlsx');
const s=Workbook.create();add(s,'任务规格',[
['模块','规格内容'],
['任务ID','queue_worker_hpa_release'],
['主软件','Kubernetes'],
['辅助工具','PowerShell7、kubectl.exe1.32.6、内置Kustomize5.5.0、Python3.12和PyYAML6.0.2'],
['输入来源','平台容量组提供当前对象与弹性策略，运行团队提供production公共标签和发布策略'],
['输入获取方式','从交接压缩包解压到Windows11本地目录'],
['原始输入文件','README.txt、current/deployment.yaml、current/hpa.yaml、autoscaling_policy.json、environment_labels.csv和release_policy.json'],
['目标输出文件','release/production与release/rollback目录、rendered_production.yaml、rendered_rollback.yaml、change_record.csv、release_plan.yaml和release_notes.txt'],
['核心操作链','核对对象与策略→修正HPA→保留Deployment业务配置→补公共标签→组织上线和撤回目录→生成两份清单→整理发布计划'],
['HPA身份','autoscaling/v2HorizontalPodAutoscaler位于queue-platform并指向apps/v1Deployment queue-worker'],
['弹性指标','同时配置CPU Resource Utilization和queue_depth External AverageValue'],
['升降行为','scaleUp与scaleDown的窗口、选择规则、Percent和Pods策略取自容量策略'],
['Deployment保留范围','metadata.labels可以补公共标签，spec与输入Deployment保持一致'],
['环境标签','production、owner和cost-center取environment_labels.csv中的production行'],
['Kustomize目录','production与rollback分别引用对应Deployment和HPA，kubectl客户端生成两份渲染清单'],
['变更记录','change_record.csv列出HPA主要字段的前后值、来源和Deployment保留状态'],
['变更窗口','窗口时区、起止与等待预算取release_policy.json中的change_window'],
['影响面','范围限于queue-platform中的queue-worker及策略列出的两个资源，不改Deployment.spec且不预期重启Pod'],
['上线与撤回','上线命令、授权上下文要求、撤回命令与撤回条件取release_policy.json'],
['观察安排','queue_depth、cpu_utilization_percent和hpa_desired_replicas边界取发布策略并与容量策略一致'],
['发布说明','release_notes.txt说明材料用途、操作安排、Deployment保留范围及客户端清单边界'],
['能力边界','不连接API Server，不声称HPA Controller已执行调度、指标采集或实际扩缩容'],
['完成条件','两套Kustomize目录构建成功，HPA符合容量策略，Deployment.spec保持不变，发布计划完整承接策略'],
['可验证点','对象身份、scaleTargetRef、副本边界、metrics、behavior、公共标签、Deployment.spec、窗口、影响面、命令、撤回条件和观察指标'],
['不适合作为评分点的内容','YAML键序、文档顺序、编辑器、临时目录、注释、排版和真实集群伸缩结果'],
],[34,150]);await finish(s,'任务规格转化','任务规格转化.xlsx');
